
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import tkinter as tk
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Toplevel, ttk
import mysql.connector as db
import editForm, tambahForm




OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame4")

mydb = None
try:
    mydb = db.connect(
    host="localhost",
    user="root",
    password="",
    database="inventaristokobuah"
    )
    print("Database berhasil terhubung")
except db.Error as err:
    print("Database gagal terhubung")
    print(err)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def create_table(editWindow, canvas):
    # Membuat koneksi ke database
    cursor = mydb.cursor()
    # Membaca data dari database
    cursor.execute("SELECT * FROM barang")

    # Mendapatkan nama kolom dari hasil query
    column_names = [desc[0] for desc in cursor.description]

    # Membuat tabel Treeview
    tree = ttk.Treeview(editWindow, columns=column_names, show='headings', height=16)

    # Lebar dan tinggi create_rectangle
    rectangle_width = 1192
    rectangle_height = 352

    # Jumlah kolom dan baris
    num_columns = len(column_names)
    num_rows = 14  # Anda bisa mengubah ini tergantung pada jumlah baris data Anda

    # Menghitung lebar dan tinggi setiap kolom dan baris
    column_width = rectangle_width // num_columns
    row_height = rectangle_height // num_rows

    # Menambahkan scrollbar vertikal
    vsb = ttk.Scrollbar(editWindow, orient="vertical", command=tree.yview)
    vsb.place(x=1230, y=150, height=rectangle_height)
    tree.configure(yscrollcommand=vsb.set)

    # Menambahkan scrollbar horizontal
    hsb = ttk.Scrollbar(editWindow, orient="horizontal", command=tree.xview)
    hsb.place(x=38, y=502, width=rectangle_width)
    tree.configure(xscrollcommand=hsb.set)

    # Menambahkan kolom ke tabel
    for col in column_names:
        tree.heading(col, text=col)
        tree.column(col, width=column_width)

    # Menambahkan data ke tabel
    for row in cursor:
        tree.insert('', 'end', values=row)

    # Menempatkan tabel ke dalam canvas
    canvas.create_window(634, 326, window=tree)

def launch():
    editWindow = Toplevel()

    editWindow.geometry("1252x656")
    editWindow.configure(bg = "#628469")


    canvas = Canvas(
        editWindow,
        bg = "#628469",
        height = 656,
        width = 1252,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        626.0,
        328.0,
        image=image_image_1
    )

    button_image_tambah = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_tambah = Button(
        editWindow,
        image=button_image_tambah,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: [print("button_1 clicked"), tambahForm.launch()],
        relief="flat"
    )
    button_tambah.place(
        x=38.000030517578125,
        y=540.599853515625,
        width=171.0,
        height=39.40020751953125
    )

    button_image_edit = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_edit = Button(
        editWindow,
        image=button_image_edit,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: [print("button_2 clicked"), editForm.launch()],
        relief="flat"
    )
    button_edit.place(
        x=543.0,
        y=541.0,
        width=171.0,
        height=39.0
    )

    button_image_hapus = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_hapus = Button(
        editWindow,
        image=button_image_hapus,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_hapus.place(
        x=1059.0,
        y=541.0,
        width=171.0,
        height=39.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        editWindow,
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: [print("button_4 clicked"), editWindow.destroy()],
        relief="flat"
    )
    button_4.place(
        x=17.0,
        y=23.0,
        width=43.0,
        height=43.0
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        1111.0044021606445,
        89.9802360534668,
        image=entry_image_1
    )
    entry_1 = Entry(
        editWindow,
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0,
        font=("Inter Bold", 14 * -1)
    )
    entry_1.place(
        x=1000.0,
        y=75.0,
        width=220.00880432128906,
        height=30.960472106933594
    )

    canvas.create_text(
        1001.0,
        49.0,
        anchor="nw",
        text="Cari:",
        fill="#FFFFFF",
        font=("Inter Bold", 14 * -1)
    )

    canvas.create_rectangle(
        38.0,
        150.0,
        1230.0,
        502.0,
        fill="#D9D9D9",
        outline="")
    
    create_table(editWindow, canvas)
    editWindow.resizable(False, False)
    editWindow.mainloop()