
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import mysql.connector as db


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\micha\OneDrive\Desktop\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

mydb = None
try:
    mydb = db.connect(
    host="localhost",
    user="root",
    password="",
    database="inventaristokobuah"
    )
    print("Database berhasil terhubung")
except db.Error as err:
    print("Database gagal terhubung")
    print(err)

def login():
    username = entry_1.get()
    password = entry_2.get()
    cursor = mydb.cursor()
    cursor.execute("SELECT * FROM pengguna WHERE username = %s AND password = %s", (username, password))
    result = cursor.fetchall()
    if len(result) == 0:
        print("Username atau password salah")
        canvas.create_text(
            202.7919921875,
            340,
            anchor="nw",
            text="Username atau Password salah.",
            fill="red",
            font=("Inter Bold", 12 * -1),
        )
    else:
        print("Login berhasil")
        mainWindow.destroy()
        import menu

mainWindow = Tk()

mainWindow.geometry("763x464")
mainWindow.configure(bg = "#628469")


canvas = Canvas(
    mainWindow,
    bg = "#628469",
    height = 464,
    width = 763,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    381.0,
    232.0,
    image=image_image_1
)

canvas.create_text(
    340.0,
    42.0,
    anchor="nw",
    text="Login",
    fill="#FFFFFF",
    font=("Inter Bold", 41 * -1)
)

canvas.create_text(
    240.0,
    111.0,
    anchor="nw",
    text="Silahkan Masukkan Username Dan Password",
    fill="#FFFFFF",
    font=("Inter Bold", 15 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    377.3543243408203,
    210.61190795898438,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font = ("Calibri",18)
)
entry_1.place(
    x=195,
    y=190,
    width=365,
    height=40
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    377.3543243408203,
    302.1113586425781,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font = ("Calibri",18),
    show = "*"
)
entry_2.place(
    x=195,
    y=280,
    width=365,
    height=40
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: login(),
    relief="flat"
)
button_1.place(
    x=275.0,
    y=367.0,
    width=206.0,
    height=62.0
)

canvas.create_text(
    202.7919921875,
    157.074951171875,
    anchor="nw",
    text="Username : ",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    202.7919921875,
    248.57440185546875,
    anchor="nw",
    text="Password :",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

mainWindow.bind("<Return>", lambda event: login())
mainWindow.title("Login")
mainWindow.resizable(False, False)
mainWindow.mainloop()
