
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\micha\OneDrive\Desktop\build\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("578x363")
window.configure(bg = "#628469")


canvas = Canvas(
    window,
    bg = "#628469",
    height = 363,
    width = 578,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    289.0,
    186.52850341796875,
    image=image_image_1
)

canvas.create_text(
    255.0,
    12.0,
    anchor="nw",
    text="TAMBAH\n",
    fill="#FFFFFF",
    font=("Sansation Regular", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=9.0,
    y=12.0,
    width=52.0,
    height=40.0
)

entry_image_id = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_id = canvas.create_image(
    72.72333145141602,
    119.1829481124878,
    image=entry_image_id
)
entry_id = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_id.place(
    x=31,
    y=109.884033203125,
    width=80.58936309814453,
    height=18.597829818725586
)

entry_image_masuk = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    347.9467582702637,
    118.78115367889404,
    image=entry_image_masuk
)
entry_masuk = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_masuk.place(
    x=287.669921875,
    y=110.48223876953125,
    width=120,
    height=18.597829818725586
)

entry_image_kadaluarsa = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_kadaluarsa = canvas.create_image(
    486.96479415893555,
    118.78115367889404,
    image=entry_image_kadaluarsa
)
entry_kadaluarsa = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_kadaluarsa.place(
    x=426.6879577636719,
    y=110.48223876953125,
    width=120.55367279052734,
    height=18.597829818725586
)

entry_image_nama = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_nama = canvas.create_image(
    202.13085174560547,
    118.78115367889404,
    image=entry_image_nama
)
entry_nama = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_nama.place(
    x=134,
    y=110.48223876953125,
    width=136.27928161621094,
    height=18.597829818725586
)

entry_image_jual = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_jual = canvas.create_image(
    103.07630157470703,
    193.5,
    image=entry_image_jual
)
entry_jual = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_jual.place(
    x=29.92864990234375,
    y=185.0,
    width=145.29530334472656,
    height=19.0
)

canvas.create_text(
    28.92864990234375,
    87.1876220703125,
    anchor="nw",
    text="ID Buah : ",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    132.9912109375,
    90.80364990234375,
    anchor="nw",
    text="Nama Buah :",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    33.75,
    161.9197998046875,
    anchor="nw",
    text="Harga jual :",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

entry_image_beli = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_beli = canvas.create_image(
    276.24610137939453,
    193.5133924484253,
    image=entry_image_beli
)
entry_beli = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_beli.place(
    x=207.31308889389038,
    y=185.2144775390625,
    width=137.8660249710083,
    height=18.597829818725586
)

canvas.create_text(
    207.72332763671875,
    161.9197998046875,
    anchor="nw",
    text="Harga Beli :",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

entry_image_jual = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_jual = canvas.create_image(
    449.41568756103516,
    193.9151258468628,
    image=entry_image_jual
)
entry_jual = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_jual.place(
    x=380.482675075531,
    y=184.6162109375,
    width=137.8660249710083,
    height=18.597829818725586
)

canvas.create_text(
    380.8931579589844,
    162.321533203125,
    anchor="nw",
    text="Jumlah(kg) :",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    285.669921875,
    87.1876220703125,
    anchor="nw",
    text="Tggl masuk :",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    424.6879577636719,
    85.5804443359375,
    anchor="nw",
    text="Tggl Kadaluarsa :",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=208.0,
    y=303.0,
    width=142.0,
    height=46.0
)
window.resizable(False, False)
window.mainloop()
